### ISSUE TITLE
Build task doesn't blow away existing files

### ISSUE THREAD

**Issue by tareiking** [sennza/Flair#110]
Ran build task today and noticed that a file which was deleted from the project, was still included in the `release` build folder.

This was a problem due to the deleted file containing already declared functions and whitescreening the site.

@BronsonQuick Probably best to blow away the releases folder each time we run `grunt build` until we add some kind of versioning into the build task, what do you think?

**Comment by BronsonQuick** [comment]
@tareiking I've already got versioning built in: https://github.com/sennza/Flair/blob/master/Gruntfile.js#L50 all you should need to do is bump https://github.com/sennza/Flair/blob/master/package.json#L3 and it should work. Let me know if that works for you as I haven't tested that since I added that early last year :+1:

**Comment by BronsonQuick** [comment]
I just tested this then and it works as expected with the versioning increments. e.g.
![screen shot 2015-01-05 at 7 52 39 pm](https://cloud.githubusercontent.com/assets/1377956/5611618/8c31cec0-9514-11e4-9d10-679621cd35a7.png)

Note that the build task also factors in the `name` hence the `tdwag-theme.zip` :smile:

**Comment by BronsonQuick** [comment]
Also, I'm open to altering the `build` task to check if a folder for the `version` exists and deleting it before running the `build` but I wrote the `build` task with the mindset of someone using this for releasing themes to .org or a marketplace.

I know internally we aren't versioning themes as we're doing agile theming :smile:

**Comment by BronsonQuick** [comment]
I've just edited the readme with more details about the build task that I'd missed. https://github.com/sennza/Flair/blob/master/README.md#package-as-zip props @tareiking

**Comment by tareiking** [comment]
Oh props. I didn't even think to check how the versioning support worked props @BronsonQuick

**Comment by BronsonQuick** [comment]
:+1: #illcodewithyou
