### ISSUE TITLE
Cryptic error when first running

### ISSUE THREAD

**Issue by rmccue** [sennza/Flair#48]
If you "forget" to do the initial setup steps of `npm install` and `bower install`, running `grunt` gives you a "Fatal error: Unable to find local Grunt" error. This is a wee bit cryptic, and it'd be nice to catch that and fix it.

**Comment by BronsonQuick** [comment]
I've had a crack at trying to catch this error and throwing a better notice but it doesn't look like I do that :disappointed: [grunt.fail](http://gruntjs.com/api/grunt.fail) didn't help me and I couldn't find much on StackExchange so I'm gonna have to close this out.
