### ISSUE TITLE
Hide comments option?

### ISSUE THREAD

**Issue by tareiking** [sennza/Flair#60]
Periodically get asked to hide comments on all pages, which is normally done by commenting out or removing the relevant section within template files.

Is this something we should add as an ``add_theme_support`` conditional?

IE: ``add_theme_support('hide_comments_on', array('pages', 'posts', 'all')``

**Comment by BronsonQuick** [comment]
I think I've decided once again that I don't think this is something that should be handled in our starter theme. This can be easily fixed inside the theme itself.
