### ISSUE TITLE
Add contact with map page template

### ISSUE THREAD

**Issue by tareiking** [sennza/Flair#72]
Like this: http://www.sennza.com.au/contact/
- This usage also support interchange to change the map to an image when on mobile

**Comment by BronsonQuick** [comment]
I'm gonna close this issue as I think it's theme specific and shouldn't be in Flair. We'll use HMD's CMB's for this in client themes going forward: https://github.com/humanmade/Custom-Meta-Boxes/wiki/Location-Field-Google-Maps with a custom WordPress Page Template.
